import prisma from "../utils/prisma";
import { AppError } from "../utils/errors";
import { Prisma } from "@prisma/client";

const milestone = Number(process.env.REWARD_MILESTONE) || 5;
const discountPercent =
  Number(process.env.REWARD_DISCOUNT_PERCENT) || 10;

export const generateRewardCoupon = async () => {
  if (!Number.isInteger(milestone) || milestone <= 0) {
    throw new AppError(
      "INVALID_REWARD_CONFIG",
      "REWARD_MILESTONE must be a positive integer",
      500
    );
  }

  if (
    !Number.isInteger(discountPercent) ||
    discountPercent < 0 ||
    discountPercent > 100
  ) {
    throw new AppError(
      "INVALID_REWARD_CONFIG",
      "REWARD_DISCOUNT_PERCENT must be between 0 and 100",
      500
    );
  }

  const successfulOrderCount = await prisma.order.count();

  if (successfulOrderCount < milestone) {
    throw new AppError(
      "MILESTONE_NOT_REACHED",
      `Reward milestone has not been reached yet. ${milestone} successful orders are required.`,
      409
    );
  }

  // Find the highest milestone coupon generated so far.
  const lastGeneratedCoupon = await prisma.coupon.findFirst({
    orderBy: {
      milestoneNumber: "desc",
    },
  });

  // Generate the next milestone coupon.
  const nextMilestone = lastGeneratedCoupon
    ? lastGeneratedCoupon.milestoneNumber + milestone
    : milestone;

  if (nextMilestone > successfulOrderCount) {
    throw new AppError(
      "NO_ELIGIBLE_MILESTONE",
      "No unrewarded milestone is currently eligible",
      409
    );
  }

  const code = `REWARD-MILESTONE-${nextMilestone}`;

  try {
    return await prisma.coupon.create({
      data: {
        code,
        discountPercent,
        milestoneNumber: nextMilestone,
        status: "AVAILABLE",
      },
    });
  } catch (error) {
    // milestoneNumber and code are unique.
    // If concurrent admin requests try to generate
    // the same coupon, PostgreSQL rejects the duplicate.
    if (
      error instanceof Prisma.PrismaClientKnownRequestError &&
      error.code === "P2002"
    ) {
      throw new AppError(
        "COUPON_ALREADY_GENERATED",
        "This reward coupon was already generated by another request",
        409
      );
    }

    throw error;
  }
};
