import prisma from "../utils/prisma";

export const getAdminReport = async () => {
  /*
   * Orders are created only after successful checkout,
   * so every row in Order represents a successfully placed order.
   */
  const orders = await prisma.order.findMany({
    include: {
      items: true,
    },
    orderBy: {
      createdAt: "asc",
    },
  });

  /*
   * Purchased quantity by product.
   *
   * We use the product snapshot stored in OrderItem so that
   * the report remains understandable even if the product
   * is renamed later.
   */
  const productMap = new Map<
    string,
    {
      productId: string;
      productName: string;
      purchasedQuantity: number;
      grossRevenueInPaise: number;
    }
  >();

  let grossRevenueInPaise = 0;
  let totalDiscountsInPaise = 0;
  let netRevenueInPaise = 0;

  for (const order of orders) {
    grossRevenueInPaise += order.subtotalInPaise;
    totalDiscountsInPaise += order.discountInPaise;
    netRevenueInPaise += order.totalInPaise;

    for (const item of order.items) {
      const existing = productMap.get(item.productId);

      if (existing) {
        existing.purchasedQuantity += item.quantity;
        existing.grossRevenueInPaise += item.lineTotalInPaise;
      } else {
        productMap.set(item.productId, {
          productId: item.productId,
          productName: item.productNameSnapshot,
          purchasedQuantity: item.quantity,
          grossRevenueInPaise: item.lineTotalInPaise,
        });
      }
    }
  }

  /*
   * Coupon statistics.
   *
   * Coupons are generated by the admin and have one of:
   * AVAILABLE / REDEEMED
   */
  const [
    totalGeneratedCoupons,
    availableCoupons,
    redeemedCoupons,
  ] = await Promise.all([
    prisma.coupon.count(),

    prisma.coupon.count({
      where: {
        status: "AVAILABLE",
      },
    }),

    prisma.coupon.count({
      where: {
        status: "REDEEMED",
      },
    }),
  ]);

  return {
    totalSuccessfulOrders: orders.length,

    purchasedQuantityByProduct:
      Array.from(productMap.values()),

    grossRevenueInPaise,

    totalDiscountsInPaise,

    netRevenueInPaise,

    coupons: {
      generated: totalGeneratedCoupons,
      available: availableCoupons,
      redeemed: redeemedCoupons,
    },
  };
};